### ISSUE TITLE
파일명 관련 질문.

### ISSUE THREAD

**Issue by cjh5414** [stompesi/programmingCamp#13]
c언어 문제에서 대부분 함수명은 problem_ 이고 파일 명은 method_ 이던데 
7번 문제는 둘 다 problem 이더라구요
어떤거에 맞춰서 하면 될까요?

**Comment by stompesi** [comment]
문제 7번이 잘못 되었습니다.
변경해놓겠습니다.

**Comment by stompesi** [comment]
<img width="1038" alt="2015-12-26 10 50 43" src="https://cloud.githubusercontent.com/assets/1393421/12004840/cc415712-abbe-11e5-89b6-6586f97bc37d.png">
